# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹  Usage Questions
    url: https://github.com/xmnlab/feedback-linker.git/discussions
    about: |
      Use Feedback Linker's GitHub Discussions to ask "How do I do X with Feedback Linker?".
  - name: ğŸ“–  Tutorial
    url: https://github.com/xmnlab/feedback-linker.git
    about: |
      The Feedback Linker tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of Feedback Linker.
  - name: ğŸ“  Feedback Linker Code of Conduct
    url: https://github.com/xmnlab/feedback-linker.git/coc/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on Feedback Linker's GitHub.
