# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹  Usage Questions
    url: https://github.com/xmnlab/growth-plan-linker.git/discussions
    about: |
      Use Growth Plan Linker's GitHub Discussions to ask "How do I do X with Growth Plan Linker?".
  - name: ğŸ“–  Tutorial
    url: https://github.com/xmnlab/growth-plan-linker.git
    about: |
      The Growth Plan Linker tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of Growth Plan Linker.
  - name: ğŸ“  Growth Plan Linker Code of Conduct
    url: https://github.com/xmnlab/growth-plan-linker.git/coc/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on Growth Plan Linker's GitHub.
